language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-28.0.2
    - android-26

script:
    # Run the build
  - "./gradlew assembleRelease check --info"

deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew bintrayUpload
  on:
    tags: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
