name: Main

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gradle/wrapper-validation-action@v1

  create_staging_repository:
      runs-on: ubuntu-latest
      needs: [ validation ]
      name: Create staging repository
      outputs:
          repository_id: ${{ steps.create.outputs.repository_id }}
      steps:
          - id: create
            if: startsWith(github.ref, 'refs/tags/')
            uses: nexus-actions/create-nexus-staging-repo@v1.1
            with:
                username: appmattus
                password: ${{ secrets.SONATYPE_PASSWORD }}
                staging_profile_id: ${{ secrets.SONATYPE_PROFILE_ID }}
                description: ${{ github.repository }}/${{ github.workflow }}#${{ github.run_number }}

  build:
    needs: [validation, create_staging_repository]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
          distribution: 'zulu'
          java-version: '11'

    - name: Build with Gradle
      run: ./gradlew assemble check --stacktrace

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
          token: ${{secrets.CODECOV_TOKEN}}

    - name: Prepare tag properties
      run: |
          echo "${{secrets.GPG_SIGNING_SECRET_KEY_RING_FILE_BASE64}}" > ~/.gradle/sonatype-appmattus-keys.gpg.b64
          base64 -d ~/.gradle/sonatype-appmattus-keys.gpg.b64 > ~/.gradle/sonatype-appmattus-keys.gpg
          echo "${{secrets.GPG_GRADLE_PROPERTIES}}" > ~/.gradle/gradle.properties
      if: startsWith(github.ref, 'refs/tags/')

    - name: Upload tag
      if: startsWith(github.ref, 'refs/tags/')
      run: ./gradlew publish --no-daemon --no-parallel -Psigning.secretKeyRingFile=$(echo ~/.gradle/sonatype-appmattus-keys.gpg)
      env:
          SONATYPE_REPOSITORY_ID: ${{ needs.create_staging_repository.outputs.repository_id }}

    - name: Close and release tag
      if: startsWith(github.ref, 'refs/tags/')
      run: ./gradlew closeAndReleaseRepository
