name: "UI Tests"

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21, 23, 29]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2.14.3
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedCheck
