name: CI

on:
  push:
    branches:
    - master
    tags:
    - '*'
  pull_request:
    branches:
    - master

env:
  CI: "true"

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [17, 23, 29]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedCheck
